title: "A Technology Intelligence"
name: "TechnoBureau"
short_name: "TB"
description: A Tutorial for Linux learning enthuaist.
media: https://ganapathichidambaram.github.io
host: 127.0.0.1
port: 4029
feedback_email: ganapathi.rj@gmail.com
sidebar_accordion: true
markdown: redcarpet
show_audience_label: true
output: web
paginate: 15
timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

format: web
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo

url: https://ganapathichidambaram.github.io

exclude:
  - _drafts
  - .idea
  - .vscode
  - _site
  - vendor

# this enables collections
collections:
  restapicourse:
    output: false
  publishingapidocs:
    output: false
# these are defaults that get applied to each page or post's frontmatter. leave as is.
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      author: <a href='/aboutme/'>Ganapathi Chidambaram</a>
  -
    scope:
      path: ""
      type: "tooltips_demo"
    values:
      layout: "page"
      search: true

#  -
#    scope:
#      path: ""
#      type: "youngadultnovel"
#    values:
#      layout: "page_yanovel"

target: web

## itunes feed settings

####### Algolia configuration ###########
#algolia:
#  application_id: XUM0ZBII9L
#  index_name: idratherbewriting
#  search_only_api_key: aa11df1f45809fcdfb5b7bc89a301682
#  files_to_exclude:
#    - ./*.html
#    - redirects/*
#    - files/**/*
#    - pages/category-archives/*
#    - pages/date-based-archives/*
#  nodes_to_index: 'p,.description'
#eventbrite_public_token: FUQRFCCTNLYIUXJZQCSV

####### jekyll seo tag configuration #######
title: TechnoBureau
tagline: A Tutorial for Linux learning enthuaist.
#description: A Tutorial for Linux learning enthuaist.
#url: https://ganapathichidambaram.github.io
author:
  twitter: ganapathi_raja
twitter:
  username: TechnoBureau
  card: summary

logo: https://ganapathichidambaram.github.io/images/site-logo-min.jpg

social:
  name: Ganapathi Chidambaram
  links:
    - https://twitter.com/ganapathi_raja
    - https://www.facebook.com/GanapathiChidambaram
    - https://www.linkedin.com/in/GanapathiChidambaram/
    - https://github.com/ganapathichidambaram

#facebook:
#  app_id: 247143161970549
#  publisher: 3968842976464

#webmaster_verifications:
#  google: i1qwK1LFgKEQHUtpm8o7OOOeK9i54NUQwKR4vXRqlFs
#  bing: 352636FE6BAFC693A6938983FC6A227E

lang: en_US
language: "en"
lang_direction: "ltr"
color: "#590C12"
