# Site Info
title: Ganapathi Chidambaram Blog
tagline: 'A Tutorial for Linux learning enthuaist'
description: ''
baseurl: ""
url: //ganapathichidambaram.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Ganapathi Chidambaram
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 6180104 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/ganapathichidambaram
    github:    https://github.com/ganapathichidambaram
    facebook:  https://facebook.com/GanapathiChidambaram
    twitter:   https://twitter.com/ganapathi_raja
    #weibo:     
    email:     ganapathi.rj@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/categories/'
  Tags:           
    - '/tags/'  
  About:          
    - '/about/'
  
# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

hero:
  image: ''
  caption: ''

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'ganapathichidambaram' # leave blank if you don't want disqus

timezone:  Asia/Calcutta
encoding:             "utf-8"
defaults:
  -
  scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Ganapathi Chidambaram"
      category: "Linux"