name: "Ganapathi Chidambaram - Blog"
description: A Tutorial for Linux learning enthuaist.
host: 127.0.0.1
port: 4030
feedback_email: ganapathi.rj@gmail.com
sidebar_accordion: true

encoding: ISO-8859-1

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 syntax_highlighter: rouge
 show_audience_label: true

# encoding: ISO-8859-1

timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

exclude:
  - _drafts
  - .idea
  - _site
  - _posts
  - pages

# this enables collections
collections:
  restapicourse:
    output: true


# these are defaults that get applied to each page or post's frontmatter. leave as is.
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "restapicourse"
    values:
      comments: true
      search: true

target: pdf
