site_name: TechnoBureau -  Your Gateway to Tech Excellence
site_description: 'Unleashing the Power of Technology for a Connected Future'
site_author : Ganapathi Chidambaram
site_url: https://technobureau.com
docs_dir: en-us
#repo_url: https://github.com/ganapathichidambaram/ganapathichidambaram.github.io
#repo_name: ganapathichidambaram/ganapathichidambaram.github.io
copyright: Copyright &copy; 2016 - 2023 TechnoBureau
edit_uri: ""
theme:
  name: material
  custom_dir: .overrides
  favicon: favicon.ico
  #logo: TechnoBureau.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: technobureau
      #primary: 'blue grey'
      #accent: 'brown'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
     # primary: 'blue grey'
     # accent: 'brown'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font: false
    #text: Source Sans Pro
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
  #  - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.prune
    - content.tabs.link
  icon:
    admonition:
      note: fontawesome/solid/book-open
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - tags
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
      timezone: Asia/Kolkata
      exclude:
        - index.md
  - pdf-with-js:
        enable: true # should enable only when need PDF files
        add_download_button: false
        display_header_footer: true
        header_template: >-
            <div style="font-size:8px; margin:auto; color:lightgray;">
                <span class="title"></span>
            </div>
        footer_template: >-
            <div style="font-size:8px; margin:auto; color:lightgray;">
                Page <span class="pageNumber"></span> of
                <span class="totalPages"></span>
            </div>

extra:
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:ganapathi@technobureau.com
    - icon: fontawesome/brands/github
      link: https://github.com/ganapathichidambaram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ganapathichidambaram/
    - icon: fontawesome/brands/instagram
      link: https://twitter.com/ganapathi_raja
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/ganapathichidambaram

markdown_extensions:
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra_css:
  - stylesheets/extra.css